Product:
    type: entity
    table: Product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        imgurl:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
            column: imgUrl
    lifecycleCallbacks: {  }
