User:
    type: entity
    table: User
    uniqueConstraints:
        USER_LOGIN_UNIQUE:
            columns:
                - login
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        firstname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: firstName
        lastname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: lastName
        civility:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        address:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        postalcode:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: postalCode
        country:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        mail:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        phonenumber:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: phoneNumber
    lifecycleCallbacks: {  }
